#!/bin/sh
#PBS -V # export all environment variables to the batch job.
#PBS -d . # set working directory to .
#PBS -q sq # submit to the parallel queue
#PBS -l walltime=replace_time_estimate # Maximum wall time for the job.
#PBS -A Research_Project-148395 # research project to submit under. 
#PBS -l procs=1 # specify number of processors.
#PBS -m e -M p.halloran@exeter.ac.uk # email me at job completion
 

# Commands you wish to run must go here, after the PBS directives
./run_gotm
