#!/bin/bash

#export DEFINES="-DINCLUDE_PELCO2 -DINCLUDE_BENCO2 -DINCLUDE_BENPROFILES"
#export DEFINES="-DINCLUDE_TRACK"

./GenerateGlobalBFMF90Code $DEFINES -read ./GlobalDefsBFM.model \
		-from ../proto -to .  -actions statemem allocmem netcdfmem \
		-to . -actions headermem  


